/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mathfp.restaurante.gui;

import br.com.mathfp.controller.RestauranteFacade;
import br.com.mathfp.restaurante.bd.RestauranteBD;
import br.com.mathfp.restaurante.entidade.Pedido;
import br.com.mathfp.restaurante.enums.Bebida;
import br.com.mathfp.restaurante.enums.TipoPrato;


/**
 *
 * @author Matheus
 */
public class RestauranteGUI extends javax.swing.JFrame {

    /**
     * Creates new form RestauranteGUI
     */
    public RestauranteGUI() {
        initComponents();
        RestauranteBD.inicializarBD();
        operacaoAtualizarInterface();
        popularCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jtpAbas = new javax.swing.JTabbedPane();
        jpClientes = new javax.swing.JPanel();
        jscpClientes = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        jpMenuCliente = new javax.swing.JPanel();
        jbInserirCliente = new javax.swing.JButton();
        jbAlterarCliente = new javax.swing.JButton();
        jbRemoverCliente = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jpMenuPedido = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jcbComida = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcbBebida = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jbInserirPedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpPedidos = new javax.swing.JPanel();
        jscpPedidos = new javax.swing.JScrollPane();
        jtPedidos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbAlterar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtfValor1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbComida1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jcbBebida1 = new javax.swing.JComboBox<>();
        jbSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscpClientes.setViewportView(jtClientes);

        jbInserirCliente.setText("Inserir Cliente");
        jbInserirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirClienteActionPerformed(evt);
            }
        });

        jbAlterarCliente.setText("Alterar");
        jbAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarClienteActionPerformed(evt);
            }
        });

        jbRemoverCliente.setText("Remover");
        jbRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverClienteActionPerformed(evt);
            }
        });

        jbAtualizar.setIcon(new javax.swing.ImageIcon("G:\\TreinamentoJavaBrq\\Image\\icons8-refresh-30.png")); // NOI18N
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuClienteLayout = new javax.swing.GroupLayout(jpMenuCliente);
        jpMenuCliente.setLayout(jpMenuClienteLayout);
        jpMenuClienteLayout.setHorizontalGroup(
            jpMenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbInserirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbAlterarCliente)
                .addGap(18, 18, 18)
                .addComponent(jbRemoverCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuClienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpMenuClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbAlterarCliente, jbInserirCliente, jbRemoverCliente});

        jpMenuClienteLayout.setVerticalGroup(
            jpMenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuClienteLayout.createSequentialGroup()
                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpMenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInserirCliente)
                    .addComponent(jbAlterarCliente)
                    .addComponent(jbRemoverCliente))
                .addGap(39, 39, 39))
        );

        jLabel6.setText("Prato");

        jcbComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Bebida");

        jcbBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Valor");

        jbInserirPedido.setText("Inserir Pedido");
        jbInserirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuPedidoLayout = new javax.swing.GroupLayout(jpMenuPedido);
        jpMenuPedido.setLayout(jpMenuPedidoLayout);
        jpMenuPedidoLayout.setHorizontalGroup(
            jpMenuPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfValor))
                .addGap(39, 39, 39)
                .addGroup(jpMenuPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuPedidoLayout.createSequentialGroup()
                        .addComponent(jbInserirPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpMenuPedidoLayout.createSequentialGroup()
                        .addGroup(jpMenuPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbComida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpMenuPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jcbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jpMenuPedidoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbInserirPedido, jcbBebida, jcbComida, jtfValor});

        jpMenuPedidoLayout.setVerticalGroup(
            jpMenuPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMenuPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbInserirPedido)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel5.setText("Cliente");

        jLabel4.setText("Pedido");

        javax.swing.GroupLayout jpClientesLayout = new javax.swing.GroupLayout(jpClientes);
        jpClientes.setLayout(jpClientesLayout);
        jpClientesLayout.setHorizontalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscpClientes)
                    .addGroup(jpClientesLayout.createSequentialGroup()
                        .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpMenuCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpMenuPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpClientesLayout.setVerticalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClientesLayout.createSequentialGroup()
                        .addComponent(jpMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpMenuPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpClientesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jtpAbas.addTab("Clientes", jpClientes);

        jtPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPedidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtPedidosFocusGained(evt);
            }
        });
        jscpPedidos.setViewportView(jtPedidos);

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbRemover.setText("Remover");
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        jLabel9.setText("Valor");

        jLabel10.setText("Prato");

        jcbComida1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Bebida");

        jcbBebida1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbSelecionar.setText("Selecionar");
        jbSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(167, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jcbComida1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jcbBebida1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbSelecionar))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcbBebida1, jcbComida1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jbSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbComida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBebida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbRemover))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jpPedidosLayout = new javax.swing.GroupLayout(jpPedidos);
        jpPedidos.setLayout(jpPedidosLayout);
        jpPedidosLayout.setHorizontalGroup(
            jpPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscpPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPedidosLayout.setVerticalGroup(
            jpPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jtpAbas.addTab("Pedidos", jpPedidos);

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpAbas)
                .addContainerGap())
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpAbas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPedidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPedidosFocusGained
        int selecionado = jtClientes.getSelectedRow();
        if (selecionado >= 0) {
            String idString = (String) jtClientes.getValueAt(
                    selecionado, 0);
            jtPedidos.setModel(RestauranteFacade.
                    gerarModeloTabelaPedidos(idString));
        } else {
            jtpAbas.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jtPedidosFocusGained

    private void setarCamposPedidos() {
        if (jtPedidos.getSelectedRow() != -1) {
            int linhaDoPedido = jtPedidos.getSelectedRow();
            Pedido pedido = getPedidoPorLinha(linhaDoPedido);
            jtfValor1.setText(pedido.getValor());
            jcbComida1.setSelectedItem(pedido.getPrato().getTipoPrato());
            jcbBebida1.setSelectedItem(pedido.getBedida().getBebida());
        }
    }


    private void jbInserirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirClienteActionPerformed
        RestauranteFacade.operacaoInserirCliente();
        operacaoAtualizarInterface();
    }//GEN-LAST:event_jbInserirClienteActionPerformed

    private void jbRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverClienteActionPerformed
        if (jtClientes.getSelectedRow() != -1) {
            int linhaDoCliente = jtClientes.getSelectedRow();
            int id = Integer.parseInt((String) jtClientes.
                    getValueAt(linhaDoCliente, 0));
            String nome = (String) jtClientes.
                    getValueAt(linhaDoCliente, 1);
            String cpf = (String) jtClientes.
                    getValueAt(linhaDoCliente, 2);
            String contato = (String) jtClientes.
                    getValueAt(linhaDoCliente, 3);
            RestauranteFacade.operacaoDeletarCliente(id, nome, cpf, contato);
            operacaoAtualizarInterface();
        }
    }//GEN-LAST:event_jbRemoverClienteActionPerformed

    private void jbAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarClienteActionPerformed
        if (jtClientes.getSelectedRow() != -1) {
            int linhaDoCliente = jtClientes.getSelectedRow();
            int id = Integer.parseInt((String) jtClientes.
                    getValueAt(linhaDoCliente, 0));
            String nome = (String) jtClientes.
                    getValueAt(linhaDoCliente, 1);
            String cpf = (String) jtClientes.
                    getValueAt(linhaDoCliente, 2);
            String contato = (String) jtClientes.
                    getValueAt(linhaDoCliente, 3);
            RestauranteFacade.operacaoModificarCliente(id, nome, cpf, contato);
            operacaoAtualizarInterface();
        }
    }//GEN-LAST:event_jbAlterarClienteActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        operacaoAtualizarInterface();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbInserirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirPedidoActionPerformed
        if (jtClientes.getSelectedRow() != -1) {
            int linhaDoCliente = jtClientes.getSelectedRow();
            int id = Integer.parseInt((String) jtClientes.
                    getValueAt(linhaDoCliente, 0));
            String nome = (String) jtClientes.
                    getValueAt(linhaDoCliente, 1);
            String cpf = (String) jtClientes.
                    getValueAt(linhaDoCliente, 2);
            String contato = (String) jtClientes.
                    getValueAt(linhaDoCliente, 3);
            String valor = jtfValor.getText();
            String prato = jcbComida.getSelectedItem().toString();
            String bebida = jcbBebida.getSelectedItem().toString();
            RestauranteFacade.operacaoInserirPedido(
                    id, nome, cpf, contato, valor, prato, bebida);
            jtfValor.setText("");
            jcbComida.setSelectedIndex(5);
            jcbBebida.setSelectedIndex(4);
        }
    }//GEN-LAST:event_jbInserirPedidoActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        if (jtPedidos.getSelectedRow() != -1) {
            int linhaDoPedido = jtPedidos.getSelectedRow();
            int id = Integer.parseInt((String) jtPedidos.
                    getValueAt(linhaDoPedido, 0));
            int idCliente = Integer.parseInt((String) jtPedidos.
                getValueAt(linhaDoPedido, 1));
            String prato = (String) jtPedidos.getValueAt(linhaDoPedido, 2);
            String bebida = (String) jtPedidos.getValueAt(linhaDoPedido, 3);
            String valor = (String) jtPedidos.getValueAt(linhaDoPedido, 4);
            String valorRetornado = jtfValor1.getText();
            String pratoRetornado = jcbComida1.getSelectedItem().toString();
            String bebidaRetornado = jcbBebida1.getSelectedItem().toString();
            RestauranteFacade.operacaoAtualizarPedido(
                    id, idCliente, prato, bebida,
                    valor, valorRetornado, pratoRetornado, bebidaRetornado);
            operacaoAtualizarInterfacePedidos(idCliente);
            jtfValor1.setText("");
            jcbComida1.setSelectedIndex(5);
            jcbBebida1.setSelectedIndex(4);
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        if (jtPedidos.getSelectedRow() != -1) {
            int linhaDoPedido = jtPedidos.getSelectedRow();
            int id = Integer.parseInt((String) jtPedidos.
                    getValueAt(linhaDoPedido, 0));
            int idCliente = Integer.parseInt((String) jtPedidos.
                getValueAt(linhaDoPedido, 1));
            String prato = (String) jtPedidos.getValueAt(linhaDoPedido, 2);
            String bebida = (String) jtPedidos.getValueAt(linhaDoPedido, 3);
            String valor = (String) jtPedidos.getValueAt(linhaDoPedido, 4);
            RestauranteFacade.
                    operacaoRemoverPedido(id, idCliente, prato, bebida, valor);
            operacaoAtualizarInterfacePedidos(idCliente);
        }
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jbSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarActionPerformed
        setarCamposPedidos();
    }//GEN-LAST:event_jbSelecionarActionPerformed

    private Pedido getPedidoPorLinha(int linha) {
        int id = Integer.parseInt((String) jtPedidos.getValueAt(linha, 0));
        int idCliente = Integer.parseInt((String) jtPedidos.
                getValueAt(linha, 1));
        String prato = (String) jtPedidos.getValueAt(linha, 2);
        String bebida = (String) jtPedidos.getValueAt(linha, 3);
        String valor = (String) jtPedidos.getValueAt(linha, 4);
        Pedido pedido = RestauranteFacade.
                operacaoRetornarPedido(id, idCliente, prato, bebida, valor);
        return pedido;
    }

    private void operacaoAtualizarInterfacePedidos(int idCliente) {
        jtPedidos.setModel(RestauranteFacade.
                gerarModeloAtualizarTabelaPedidos(idCliente));
        setarCamposPedidos();
    }

    private void operacaoAtualizarInterface() {
        jtClientes.setModel(RestauranteFacade.
                operacaoAtualizarInterfaceCliente());
    }

    private void popularCombos() {
        jcbComida.removeAllItems();
        for (TipoPrato tp : TipoPrato.values()) {
            jcbComida.addItem(tp.getTipoPrato());
        }
        jcbBebida.removeAllItems();
        for (Bebida bebida : Bebida.values()) {
            jcbBebida.addItem(bebida.getBebida());
        }

        jcbComida1.removeAllItems();
        for (TipoPrato tp : TipoPrato.values()) {
            jcbComida1.addItem(tp.getTipoPrato());
        }
        jcbBebida1.removeAllItems();
        for (Bebida bebida : Bebida.values()) {
            jcbBebida1.addItem(bebida.getBebida());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestauranteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestauranteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestauranteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestauranteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestauranteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAlterarCliente;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbInserirCliente;
    private javax.swing.JButton jbInserirPedido;
    private javax.swing.JButton jbRemover;
    private javax.swing.JButton jbRemoverCliente;
    private javax.swing.JButton jbSelecionar;
    private javax.swing.JComboBox<String> jcbBebida;
    private javax.swing.JComboBox<String> jcbBebida1;
    private javax.swing.JComboBox<String> jcbComida;
    private javax.swing.JComboBox<String> jcbComida1;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpMenuCliente;
    private javax.swing.JPanel jpMenuPedido;
    private javax.swing.JPanel jpPedidos;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JScrollPane jscpClientes;
    private javax.swing.JScrollPane jscpPedidos;
    private javax.swing.JTable jtClientes;
    private javax.swing.JTable jtPedidos;
    private javax.swing.JTextField jtfValor;
    private javax.swing.JTextField jtfValor1;
    private javax.swing.JTabbedPane jtpAbas;
    // End of variables declaration//GEN-END:variables
}
